import { MemberUser, Transaction, JourneyEvent } from "./types";

export const generateMockUsers = (): MemberUser[] => [
  {
    id: "1",
    name: "Budi Santoso",
    email: "budi.santoso@email.com",
    userId: "USR-2024-001",
    category: "REXTRA Club",
    tier: "Pro",
    startDate: new Date("2024-08-15"),
    endDate: new Date("2025-08-15"),
    remainingDays: 207,
    autoRenew: true,
    lastPurchasePrice: 300000,
    lastPurchaseDuration: 12,
    validityStatus: "Aktif",
    tokenBalance: 450,
    pointsBalance: 1250,
    entitlementCount: 25,
  },
  {
    id: "2",
    name: "Siti Aminah",
    email: "siti.aminah@email.com",
    userId: "USR-2024-002",
    category: "REXTRA Club",
    tier: "Basic",
    startDate: new Date("2024-09-10"),
    endDate: new Date("2025-03-10"),
    remainingDays: 48,
    autoRenew: false,
    lastPurchasePrice: 150000,
    lastPurchaseDuration: 6,
    validityStatus: "Aktif",
    tokenBalance: 120,
    pointsBalance: 500,
    entitlementCount: 15,
  },
  {
    id: "3",
    name: "Andi Wijaya",
    email: "andi.wijaya@email.com",
    userId: "USR-2024-003",
    category: "Trial Club",
    tier: "Starter",
    startDate: new Date("2025-01-05"),
    endDate: new Date("2025-02-05"),
    remainingDays: 5,
    autoRenew: false,
    lastPurchasePrice: 0,
    lastPurchaseDuration: 1,
    validityStatus: "Expiring",
    tokenBalance: 50,
    pointsBalance: 100,
    entitlementCount: 10,
  },
  {
    id: "4",
    name: "Rini Kusuma",
    email: "rini.kusuma@email.com",
    userId: "USR-2024-004",
    category: "Non-Club",
    tier: "Standard",
    startDate: new Date("2024-01-15"),
    endDate: undefined,
    remainingDays: 0,
    autoRenew: false,
    lastPurchasePrice: 0,
    lastPurchaseDuration: 0,
    validityStatus: "Aktif",
    tokenBalance: 0,
    pointsBalance: 0,
    entitlementCount: 5,
  },
  {
    id: "5",
    name: "Dedi Prakoso",
    email: "dedi.prakoso@email.com",
    userId: "USR-2024-005",
    category: "REXTRA Club",
    tier: "Max",
    startDate: new Date("2024-09-20"),
    endDate: new Date("2025-09-20"),
    remainingDays: 242,
    autoRenew: true,
    lastPurchasePrice: 500000,
    lastPurchaseDuration: 12,
    validityStatus: "Aktif",
    tokenBalance: 980,
    pointsBalance: 5000,
    entitlementCount: 35,
  },
  {
    id: "6",
    name: "Maya Sari",
    email: "maya.sari@email.com",
    userId: "USR-2024-006",
    category: "REXTRA Club",
    tier: "Basic",
    startDate: new Date("2024-10-10"),
    endDate: new Date("2025-01-10"),
    remainingDays: -14,
    autoRenew: false,
    lastPurchasePrice: 75000,
    lastPurchaseDuration: 3,
    validityStatus: "Expired",
    tokenBalance: 0,
    pointsBalance: 300,
    entitlementCount: 0,
  },
];

export const generateMockJourneyEvents = (userId: string): JourneyEvent[] => [
  {
    id: "1",
    date: new Date("2024-01-15T10:30:00"),
    title: "Pertama kali bergabung",
    description: "User bergabung sebagai pengguna baru",
    statusBefore: "-",
    statusAfter: "Standard",
  },
  {
    id: "2",
    date: new Date("2024-01-16T14:15:00"),
    title: "Klaim Free Trial",
    description: "User mengaktifkan periode trial",
    statusBefore: "Standard",
    statusAfter: "Starter (Trial Club)",
    duration: "30 hari",
  },
  {
    id: "3",
    date: new Date("2024-02-10T09:45:00"),
    title: "Pembelian pertama (First Purchase)",
    description: "Upgrade ke paket berbayar",
    statusBefore: "Starter",
    statusAfter: "Pro (REXTRA Club)",
    duration: "12 bulan",
    total: 300000,
    promoCode: "NEWUSER20",
    promoDiscount: 60000,
  },
  {
    id: "4",
    date: new Date("2024-08-15T08:00:00"),
    title: "Renewal otomatis",
    description: "Perpanjangan membership otomatis",
    statusBefore: "Pro",
    statusAfter: "Pro (REXTRA Club)",
    duration: "12 bulan",
    total: 270000,
    promoCode: "LOYAL10",
    promoDiscount: 30000,
  },
  {
    id: "5",
    date: new Date("2025-08-15T00:00:00"),
    title: "Berakhir / Renewal berikutnya",
    description: "Jadwal berakhir atau perpanjangan",
    statusBefore: "Pro",
    statusAfter: "Pro",
    isFuture: true,
  },
];

export const generateMockTransactions = (): Transaction[] => [
  {
    id: "1",
    referenceId: "TRX-2024-08-001234",
    date: new Date("2024-08-15T08:00:23"),
    user: { name: "Budi Santoso", email: "budi@email.com", userId: "USR-2024-001" },
    eventType: "Renewal",
    statusBefore: "Pro",
    statusAfter: "Pro",
    category: "REXTRA Club",
    duration: "12 bulan",
    basePrice: 300000,
    durationDiscount: 30000,
    promoCode: "LOYAL10",
    promoDiscount: 20000,
    adminFee: 20000,
    totalPaid: 270000,
    paymentMethod: "E-Wallet (GoPay)",
    paymentGatewayRef: "GOPAY-20240815-ABC123",
    paymentStatus: "Berhasil",
    tokenGiven: 480,
    pointsGiven: 2500,
    paymentTimeline: [
      { time: "08:00:23", status: "Transaksi dibuat" },
      { time: "08:01:45", status: "Menunggu pembayaran" },
      { time: "08:05:12", status: "Pembayaran berhasil" },
      { time: "08:05:18", status: "Membership diperbarui" },
      { time: "08:05:20", status: "Benefit diberikan" },
    ],
  },
  {
    id: "2",
    referenceId: "TRX-2024-03-005678",
    date: new Date("2024-03-10T14:20:00"),
    user: { name: "Siti Aminah", email: "siti@email.com", userId: "USR-2024-002" },
    eventType: "Upgrade",
    statusBefore: "Basic",
    statusAfter: "Pro",
    category: "REXTRA Club",
    duration: "6 bulan",
    basePrice: 180000,
    durationDiscount: 0,
    promoCode: "UPGRADE",
    promoDiscount: 20000,
    adminFee: 0,
    totalPaid: 160000,
    paymentMethod: "Bank Transfer (BCA)",
    paymentGatewayRef: "BCA-20240310-XYZ456",
    paymentStatus: "Berhasil",
    tokenGiven: 240,
    pointsGiven: 1600,
    paymentTimeline: [
      { time: "14:20:00", status: "Transaksi dibuat" },
      { time: "14:25:00", status: "Pembayaran berhasil" },
      { time: "14:25:05", status: "Membership diupgrade" },
    ],
  },
  {
    id: "3",
    referenceId: "TRX-2024-02-009123",
    date: new Date("2024-02-05T09:30:00"),
    user: { name: "Andi Wijaya", email: "andi@email.com", userId: "USR-2024-003" },
    eventType: "Purchase",
    statusBefore: "Standard",
    statusAfter: "Basic",
    category: "REXTRA Club",
    duration: "3 bulan",
    basePrice: 90000,
    durationDiscount: 0,
    promoDiscount: 0,
    adminFee: 0,
    totalPaid: 90000,
    paymentMethod: "Credit Card (Visa)",
    paymentStatus: "Menunggu",
    tokenGiven: 0,
    pointsGiven: 0,
    paymentTimeline: [
      { time: "09:30:00", status: "Transaksi dibuat" },
      { time: "09:30:05", status: "Menunggu pembayaran" },
    ],
  },
  {
    id: "4",
    referenceId: "TRX-2024-01-012456",
    date: new Date("2024-01-16T14:15:00"),
    user: { name: "Rini Kusuma", email: "rini@email.com", userId: "USR-2024-004" },
    eventType: "Trial Start",
    statusBefore: "Standard",
    statusAfter: "Starter",
    category: "Trial Club",
    duration: "30 hari",
    basePrice: 0,
    durationDiscount: 0,
    promoDiscount: 0,
    adminFee: 0,
    totalPaid: 0,
    paymentMethod: "-",
    paymentStatus: "Berhasil",
    tokenGiven: 50,
    pointsGiven: 100,
    paymentTimeline: [
      { time: "14:15:00", status: "Trial diaktifkan" },
      { time: "14:15:05", status: "Benefit diberikan" },
    ],
  },
  {
    id: "5",
    referenceId: "TRX-2024-09-015789",
    date: new Date("2024-09-20T10:00:00"),
    user: { name: "Dedi Prakoso", email: "dedi@email.com", userId: "USR-2024-005" },
    eventType: "Purchase",
    statusBefore: "Standard",
    statusAfter: "Max",
    category: "REXTRA Club",
    duration: "12 bulan",
    basePrice: 500000,
    durationDiscount: 50000,
    promoCode: "VIP2024",
    promoDiscount: 50000,
    adminFee: 0,
    totalPaid: 400000,
    paymentMethod: "QRIS",
    paymentGatewayRef: "QRIS-20240920-DEF789",
    paymentStatus: "Berhasil",
    tokenGiven: 980,
    pointsGiven: 5000,
    paymentTimeline: [
      { time: "10:00:00", status: "Transaksi dibuat" },
      { time: "10:02:30", status: "Pembayaran berhasil" },
      { time: "10:02:35", status: "Membership diaktifkan" },
      { time: "10:02:40", status: "Benefit diberikan" },
    ],
  },
];
